### ISSUE TITLE
VideoItem content_loc player_loc are not required

### ISSUE THREAD

**Issue by anthonykozak** [nilportugues/php-sitemap#46]
content_loc and player_loc are not required, but we can use only one of them. For now the VideoItem requires both and setting one as null should avoid writing it to the sitemap.

**Comment by nilportugues** [comment]
All required fields are required by the specifications.

**Comment by anthonykozak** [comment]
No they are marked as "depends" not "required"
https://developers.google.com/webmasters/videosearch/sitemaps
<video:content_loc> Depends 
You must specify at least one of <video:player_loc> or <video:content_loc>. 
A URL pointing to the actual video media file. This file should be in .mpg, .mpeg, .mp4, .m4v, .mov, .wmv, .asf, .avi, .ra, .ram, .rm, .flv, or other video file format. 
Providing this file allows Google to generate video thumbnails and video previews, and can help Google verify your video. 
Best practice: Ensure that only Googlebot accesses your content by using a reverse DNS lookup. 
<video:player_loc> Depends 
You must specify at least one of <video:player_loc> or <video:content_loc>.



anthonykozak@gmail.com
 
From: Nil Portugués Calderó
Date: 2017-04-10 13:57
To: nilportugues/php-sitemap
CC: Anthony Kozak; Author
Subject: Re: [nilportugues/php-sitemap] VideoItem content_loc player_loc are not required (#46)
All required fields are required by the specifications.
